### PR TITLE
custom routes support

### PR DESCRIPTION
**Pull request by borowskt**
Hi, I recently needed to have a custom routes support that comes with json-server. I think it might be useful for others.

### CODE REVIEW

**Comment by GrafGenerator** [comment]
@borowskt Nice, merged this and published v0.2.0.

**Comment by windmaomao** [comment]
there's a small thing here, seems to be the customRoutes does not recognize baseUrl, so you need to specify the full path, ex. '/v1/login'

**Comment by GrafGenerator** [comment]
@windmaomao, I guess this is behavior of json-server. Or you mean it should be documented?

**Comment by windmaomao** [comment]
@GrafGenerator , i guess documentation will be just fine now. Thanks.

**Pull request merged**
