### PR TITLE
Option to suppress output messages from json-server

### PR DESCRIPTION
**Pull request by dinegri**
This change pushes the option 'quiet' to json-server, allowing you control the suppressing of messages from output.

### CODE REVIEW

**Comment by dinegri** [comment]
@GrafGenerator

**Comment by GrafGenerator** [comment]
@dinegri sorry, I forget about this one. I will manage to merge it soon.

**Comment by verto** [comment]
Hi @GrafGenerator some idea when will you publish the next version with this feature? Sorry, but we're waiting for it.

**Comment by GrafGenerator** [comment]
Hi @verto, I'm currently in the process of refactoring gulp-json-srv own messages, will manage to publish new version in 2-3 days.

**Comment by GrafGenerator** [comment]
@verto @dinegri it was long way to get this one done, sorry for this delay. v1.1 just published, it has logging functionality reworked.

**Pull request merged**
